surveyors codegen from rails generate
codeforboston/urban-league-heat-pump-accelerator pull request #113
Opened 2022-11-29 13:18 UTC by aTegart

Results from `bin/rails generate scaffold Surveyor user:references firstname:string lastname:string email:string phone:string street_address:string geocode:string city:string zipcode:string state:string role:string status:string`

Named `Surveyor` to avoid collision with devise `Users`.

Maintains foreign key reference to devise `user`.

Does not yet support filtering by role, city, etc.

2022-11-29 13:25 UTC, aTegart commented
Failing due to warning:
```Confidence: Medium
Category: Mass Assignment
Check: PermitAttributes
Message: Potentially dangerous key allowed for mass assignment
Code: params.require(:surveyor).permit(:user_id, :firstname, :lastname, :email, :phone, :street_address, :geocode, :city, :zipcode, :state, :role, :status)
File: app/controllers/surveyors_controller.rb
Line: 68
```

Should some of those params (e.g. role) be assignable only indirectly?

2022-11-30 00:51 UTC, mzagaja commented
It's not entirely clear to me which key it is refering to here, but my best guess would be `:role`. Understandbly from a security standpoint, you don't want to be able to update/assign roles from a public API endpoint. However I think separating this is a bit beyond the scope of the goal of this PR, so I'm ok with [ignoring that for now](https://brakemanscanner.org/docs/ignoring_false_positives/).

2022-11-30 00:57 UTC, mzagaja requested changes
This looks reasonable to me. The only other major change I would make here is since we won't be using them, you can safely remove all the files ending in `.html.erb` and then the associated tests with 

```sh
rm spec/views/surveyors/*.html.erb_spec.rb
rm app/views/surveyors/*.html.erb
```

2022-11-30 00:57 UTC, mzagaja commented on backend/spec/factories/surveyors.rb
> +    status { "MyString" }
@aTegart Usually before committing this I'll update the sample values here from `MyString` to something that looks like the data we'll be using. You can look at mine for an example.

2022-12-21 00:43 UTC, mzagaja approved these changes
🚀

2022-12-21 00:58 UTC, merged