Frontend issue #161 about us page
codeforboston/urban-league-heat-pump-accelerator pull request #239
Opened 2023-03-23 17:45 UTC by johndowd

-moved components into about us folder & updated imports
-created about us page
-added missing image from boston.gov website

2023-03-30 20:45 UTC, thiagobardini requested changes
Hi Jack, could you please make these changes before we merge it? Let me know if you have any questions. Thanks!

2023-03-30 20:45 UTC, thiagobardini commented on frontend/front/src/pages/Public/Pages/AboutUs/AboutUs.js
> +      <Grid item display="flex" flexDirection="column" alignItems="center" mr={4} ml={4}>
I added the code below inside the GRID:

```
sx={{
color: 'var(--color-text-1) !important'
}}
```

2023-03-30 20:45 UTC, thiagobardini commented on frontend/front/src/pages/Public/Pages/AboutUs/AboutUs.js
> +          color="#000000"
Remove color

2023-03-30 20:45 UTC, thiagobardini commented on frontend/front/src/pages/Public/Pages/AboutUs/AboutUs.js
> +          color="#000000"
Remove color

2023-03-30 20:45 UTC, thiagobardini commented on frontend/front/src/pages/Public/Pages/AboutUs/PartnerTile.js
> +      color="#000000"
Remove color

2023-03-30 20:45 UTC, thiagobardini commented on frontend/front/src/pages/Public/Pages/AboutUs/AboutUs.js
> +        <img style={{ height: 100, 'max-width': '90%', mt: 3, mb: 3 }} src={ulem} />
Remove the code below:
```
<img
  style={{ height: 100, "max-width": "90%", mt: 3, mb: 3 }}
  src={ulem}
/>
```
and replace it with this code using Box:
```

<Box
  component="img"
  src={ulem}
  sx={{
    height: 100,
    "max-width": "90%",
    mt: 3,
    mb: 3,
  }}
/>
```

2023-03-30 20:45 UTC, thiagobardini commented on frontend/front/src/pages/Public/Pages/AboutUs/PartnerTile.js
> +      <Typography marginBottom={3} paragraph={true}>
Remove paragraph={true}

2023-03-30 20:45 UTC, thiagobardini commented on frontend/front/src/pages/Public/Pages/AboutUs/PartnerTile.js
> +        />
Remove the code below:
```
       <img
          style={{ height: 100, marginBottom: 12 }}
          alt={`logo of ${partnerName}`}
          src={image}
        />
```
and replace it with this code using Box:
```

        <Box
          component="img"
          src={image}
          alt={`logo of ${partnerName}`}
          sx={{
            height: 100,
            mb: 3,
          }}
        />
```

2023-03-30 20:45 UTC, thiagobardini commented on frontend/front/src/pages/Public/Pages/AboutUs/PartnerTile.js
> +      <a
replace `<a href={website} target="_blank" rel="noopener noreferrer">`

2023-03-30 20:45 UTC, thiagobardini commented on frontend/front/src/pages/Public/Pages/AboutUs/PartnerTile.js
> +import { Box, Grid, Typography, Divider } from "@mui/material";
Remove `Divider`

2023-03-30 20:45 UTC, thiagobardini commented on frontend/front/src/pages/Public/Pages/AboutUs/AboutUs.js
> +import { Box, Grid, Typography, Divider } from "@mui/material";
Remove `Divider`

2023-04-01 16:41 UTC, johndowd commented
@thiagobardini

2023-04-01 17:39 UTC, thiagobardini approved these changes
Hey John. Good job! Thanks!

2023-04-03 14:05 UTC, merged