created model, and controller -- Matt double check
codeforboston/urban-league-heat-pump-accelerator pull request #28
Opened 2022-08-31 01:33 UTC by AlisonPAnderson

I did copious googling!  Double check please!

2022-09-06 22:37 UTC, mzagaja requested changes
Made some suggestions to clean this up before we merge it in.

2022-09-06 22:37 UTC, mzagaja commented on backend/app/models/property_assessment.rb
> +            kitchens_count: kitchens_count
```suggestion
            kitchens_count: kitchens_count,
```

2022-09-06 22:37 UTC, mzagaja commented on backend/db/migrate/20220817011608_create_property_assessments.rb
> +      t.string :kitchen_style  # is this kitchen_style2?
I would nuke the comment from this PR and fix/update the field name in a different PR.

2022-09-06 22:37 UTC, mzagaja commented on backend/Gemfile
> +  gem 'rspec'
We'll be using `rspec` but I would wait until we actually start writing tests to add the gem, there are also some other RSpec setup steps to do when you first introduce it.

2022-09-08 14:18 UTC, AlisonPAnderson commented
@mzagaja It was a whole adventure (learning experience! :) )to get my SSH set up on the linux shell so I realize I am a few days late on this commit and now there are conflicts.  My apologies! please advise!

2022-10-27 11:53 UTC, closed without merging