Randy searches
codeforboston/urban-league-heat-pump-accelerator pull request #425
Opened 2023-07-15 23:04 UTC by Rando-cal

Added searchbars for Admin:Users, Admin:Homes, Admin:Surveys.

2023-07-18 19:51 UTC, mattdelsordo requested changes

2023-07-18 19:51 UTC, mattdelsordo commented on frontend/front/src/pages/Admin/user/UserTable.js
This all looks good, but it looks like changing this table has broken the link to the individual user page when clicking on a row.

2023-08-01 03:25 UTC, Rando-cal commented on frontend/front/src/pages/Admin/user/UserTable.js
@mattdelsordo User row click issue fixed. Now it should direct to the actual user. If your are not seeing the Search bar in the table, then make sure to do "yarn add @mui/x-data-grid"

2023-08-01 03:26 UTC, Rando-cal commented
Want to meet with someone else to resolve conflicts...

2023-08-08 00:33 UTC, Rando-cal commented
@mattdelsordo @LWest001 @EfrainAD 

Can someone review this to get it through?  Thanks!!

2023-08-08 21:18 UTC, mattdelsordo commented
> @mattdelsordo @LWest001 @EfrainAD
> 
> Can someone review this to get it through? Thanks!!

Looks good to me but needs a rebase + merge conflict resolution

2023-08-15 19:56 UTC, mattdelsordo approved these changes

2023-10-18 00:58 UTC, closed without merging

2023-10-18 00:59 UTC, Rando-cal commented
I think this is moot