Responsiveness
codeforboston/urban-league-heat-pump-accelerator pull request #443
Opened 2023-08-01 23:02 UTC by LWest001

Closes #433.

- Theme file created (adminTheme.js) for working with MUI theming in the admin section.
- Use of `<Stack/>` components to break down wide rows of content (like a search bar with a button next to it) into a column at smaller breakpoints.
  - **Wide:**
![image](https://github.com/codeforboston/urban-league-heat-pump-accelerator/assets/93659375/910d0eaa-2126-4577-8137-cc3a077ce88a)
  - **Narrow:**
![image](https://github.com/codeforboston/urban-league-heat-pump-accelerator/assets/93659375/79becd1a-447b-48f7-8b54-ceda89599d37)
- Removal of some unnecessary columns in the admin tables.
- The Address in an AssignProfile and HomeTable now is a link to the home, enabling removal of Home column in those tables.
![image](https://github.com/codeforboston/urban-league-heat-pump-accelerator/assets/93659375/a53629c5-f124-4c38-a5a5-ed7164ed4658)
- AssignTable gracefully handles surveyor links with multiple surveyors. The stack of surveyor links scrolls.
  - **Wide:**
![image](https://github.com/codeforboston/urban-league-heat-pump-accelerator/assets/93659375/67adfcb5-fdc6-42f7-827b-8d69b9a1be0f)
  - **Narrow:**
![image](https://github.com/codeforboston/urban-league-heat-pump-accelerator/assets/93659375/1128a1f7-5ac2-48c6-b58e-ea3f24e7c66e)

Note: I opted not to use onRowClick function in tables that have links to other items - it seems to be impossible to have a link to other content on a row that uses onRowClick. The browser fires the onRowClick function and it overrides the inline link.

2023-08-02 00:29 UTC, thiagobardini commented
Mobile View: 
https://mui.com/material-ui/react-pagination/
https://mui.com/material-ui/react-accordion/

2023-08-07 15:44 UTC, mattdelsordo requested changes
Looks pretty good, rebase this off of main to pick up the test fixes

2023-08-07 15:44 UTC, mattdelsordo commented on frontend/front/src/pages/Admin/assignment/AssignProfile.js
> +    console.log(home);
Remove this log

2023-08-07 15:44 UTC, mattdelsordo commented on frontend/front/src/pages/Admin/assignment/AssignTable.js
> +          // onRowClick={(params) => handleRowClick(params.row)}
You can remove this if onRowClick isn't being used.

2023-08-15 19:56 UTC, mattdelsordo approved these changes

2023-08-16 23:58 UTC, LWest001 commented
This branch is just not passing the prettier checks. I'm going to merge it so that we can add those prettier changes in another branch because there are so many of them.

2023-08-16 23:58 UTC, merged