create workflows for deploying front + back end
codeforboston/urban-league-heat-pump-accelerator pull request #472
Opened 2023-09-25 01:16 UTC by mattdelsordo

I followed the example at https://github.com/nerc-project/simple-node-app and _think_ this should "just work". I ran NERC's scripts to set the required secrets on the github project, but I'm not sure where to check whether that worked.

2023-09-26 21:05 UTC, mattdelsordo commented
Forgot about the environment variables - will be adding that in.

2023-09-26 22:09 UTC, mattdelsordo commented on frontend/front/src/components/SurveyComponent/HeatPumpDropdown.js
Unfortunately I had to revert this change here because it borked the tests. The problem solved still exists so we're going to have to address it anyway: https://github.com/codeforboston/urban-league-heat-pump-accelerator/issues/469

2023-09-26 22:10 UTC, mattdelsordo commented on .github/workflows/deploy.yml
> +      build-args: |
Not 100% positive all of the "normal" secrets are going to get passed like I expect...

2023-09-26 22:34 UTC, mzagaja commented
@mattdelsordo I see secrets at 
<img width="777" alt="image" src="https://github.com/codeforboston/urban-league-heat-pump-accelerator/assets/565647/b64eeb47-335c-4a24-b993-565d5336b3bb">

2023-09-26 22:37 UTC, mzagaja commented
@mattdelsordo Can you remove the now to be unused bits in https://github.com/codeforboston/urban-league-heat-pump-accelerator/blob/main/.github/workflows/test.yml so that we aren't building images for AWS anymore as a part of the workflow.

2023-09-26 23:39 UTC, mattdelsordo commented
@mzagaja would you be able to fix the back-end security check?

2023-09-30 20:27 UTC, mattdelsordo commented
@mzagaja does this look good to merge?

2023-10-16 20:27 UTC, mzagaja commented
@mattdelsordo I was hoping to dig into this and test it today but the MassOpenCloud server space is having an issue. Hopefully it resolves soon. Meanwhile I will review from a code perspective.

2023-10-16 20:46 UTC, mzagaja requested changes
Just a couple minior changes for now. Then let's merge and test this, hopefully Mass Open Cloud will be up tomorrow.

2023-10-16 20:46 UTC, mzagaja commented on .github/workflows/deploy.yml
> +  REACT_APP_API_URL: https://bhpa-backend-boston-heat-pump-accelerator-dbab1b.apps.shift.nerc.mghpcc.org
```suggestion
  REACT_APP_API_URL: https://api.bostonhpa.org
```

2023-10-16 20:46 UTC, mzagaja commented on .github/workflows/deploy.yml
> +    branches: ['main']
```suggestion
  release:
    types: [published]
```

2023-10-16 20:47 UTC, mzagaja commented
@mattdelsordo Do you mind 👀 on the merge conflicts for the front end stuff here and then we can try taking this for a spin when MOC is ready?

2023-10-18 00:45 UTC, mzagaja approved these changes
🚀

2023-10-18 01:03 UTC, mattdelsordo commented
does 🚀 mean I should merge this or

2023-10-18 01:04 UTC, lhuhmann commented
> does 🚀 mean I should merge this or

Yes, merge it! We looked at this together tonight, but didn't want to merge it without you.

2023-10-18 01:05 UTC, merged